#define canposition			"can_position"
#define robotposition 		  	"position"
#define robotdrive           		"robotdrive"  
#define otherrobotposition 		"otherposition"
#define pathplanning		    	"pathplanning"
#define pathplanning_img		"pathplanning_img"
#define candistance                     "candistance"
